### ISSUE TITLE
ESM max length

### ISSUE THREAD

**Issue by lhallee** [zhengkangjie/ESM-AA#2]
Hello!

ESM2 uses rotary embeddings (even though it has a normal position embedding matrix it doesn't use it), so ESM2 **has no max length**. This is a very common misconception in the field, and there is a setting for it in the Huggingface implementation.
Cheers!
Logan

<img width="475" alt="image" src="https://github.com/zhengkangjie/ESM-AA/assets/72926928/eda56987-a8f7-4bfa-8df7-19b7ffe9ef01">

**Comment by zhengkangjie** [comment]
Thank you for the discussion. The maximum length of 1024 mentioned in our paper refers to the upper limit for sequences input into the model, not the maximum sequence length that the model can handle. The original ESM-2 model truncates proteins longer than 1024 amino acids to a length of 1024 during training. However, as our model needs to unfold the protein sequences, we have allowed for the input of longer protein sequences into the model.

**Comment by lhallee** [comment]
Ah, I see. Love the paper, great work!
